import React from 'react';
import { s } from '../style.js';

export default function Collection(p) {
  return (
<div style={s("height:100%; display:flex; flex-direction:column; animation:cg-fade .3s ease;")}>
          <div style={s("flex:none; padding:4px 20px 10px;")}>
            <div style={s("display:flex; justify-content:space-between; align-items:center; margin-bottom:14px;")}><div style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:800; font-size:24px; color:var(--ink);")}>Collection</div><div onClick={p.goScan} style={s("width:38px; height:38px; border-radius:50%; background:var(--ink); display:flex; align-items:center; justify-content:center; cursor:pointer;")}><svg width="16" height="16" viewBox="0 0 16 16" style={s("fill:none; stroke:var(--bg); stroke-width:1.8")} strokeLinecap="round"><path d="M8 3v10M3 8h10"/></svg></div></div>
            <div style={s("background:var(--surface); border:1px solid var(--line); border-radius:18px; padding:16px; display:flex; align-items:center; justify-content:space-between;")}><div><div style={s("font-size:11px; color:var(--muted-2);")}>Total value</div><div className="cg-num" style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:800; font-size:26px; color:var(--ink);")}>$12,480</div><div className="cg-num" style={s("font-size:12px; color:var(--pos); font-weight:600;")}>+$2,140 all-time</div></div><svg width="92" height="48" viewBox="0 0 92 48" preserveAspectRatio="none"><polyline points="0,38 18,34 36,36 54,24 72,28 92,10" style={s("fill:none; stroke:#00c2a8; stroke-width:2.5")} strokeLinecap="round" strokeLinejoin="round"/></svg></div>
          </div>
          <div style={s("flex:none; display:flex; gap:8px; padding:6px 20px 12px; overflow:hidden;")}>
            <span style={s("background:var(--ink); color:var(--bg); font-size:12px; font-weight:600; padding:8px 14px; border-radius:100px; white-space:nowrap;")}>All · 342</span>
            <span style={s("background:var(--surface); border:1px solid var(--line-2); color:var(--muted-2); font-size:12px; font-weight:600; padding:8px 14px; border-radius:100px; white-space:nowrap;")}>Pokémon</span>
            <span style={s("background:var(--surface); border:1px solid var(--line-2); color:var(--muted-2); font-size:12px; font-weight:600; padding:8px 14px; border-radius:100px; white-space:nowrap;")}>NHL</span>
            <span style={s("background:var(--surface); border:1px solid var(--line-2); color:var(--muted-2); font-size:12px; font-weight:600; padding:8px 14px; border-radius:100px; white-space:nowrap;")}>Graded</span>
          </div>
          <div style={s("flex:1; overflow:hidden; padding:0 20px;")}>
            <div style={s("display:grid; grid-template-columns:1fr 1fr; gap:12px;")}>
              <div onClick={p.goDetail} style={s("background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:10px; cursor:pointer;")}><div style={s("height:118px; border-radius:10px; background:var(--thumb); margin-bottom:9px; position:relative;")}><span style={s("position:absolute; top:7px; left:7px; background:var(--ink); color:var(--bg); font-family:'DM Mono',monospace; font-size:9px; padding:2px 6px; border-radius:6px;")}>PSA 9</span></div><div style={s("font-weight:700; font-size:13px; color:var(--ink);")}>Charizard ex</div><div className="cg-num" style={s("font-size:12px; color:var(--pos); font-weight:600;")}>$430</div></div>
              <div onClick={p.goDetail} style={s("background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:10px; cursor:pointer;")}><div style={s("height:118px; border-radius:10px; background:var(--thumb); margin-bottom:9px; position:relative;")}><span style={s("position:absolute; top:7px; left:7px; background:var(--ink); color:var(--bg); font-family:'DM Mono',monospace; font-size:9px; padding:2px 6px; border-radius:6px;")}>PSA 9.5</span></div><div style={s("font-weight:700; font-size:13px; color:var(--ink);")}>C. Bedard RC</div><div className="cg-num" style={s("font-size:12px; color:var(--pos); font-weight:600;")}>$310</div></div>
              <div onClick={p.goDetail} style={s("background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:10px; cursor:pointer;")}><div style={s("height:118px; border-radius:10px; background:var(--thumb); margin-bottom:9px; position:relative;")}><span style={s("position:absolute; top:7px; left:7px; background:#5b6cff; color:#fff; font-family:'DM Mono',monospace; font-size:9px; padding:2px 6px; border-radius:6px;")}>RAW</span></div><div style={s("font-weight:700; font-size:13px; color:var(--ink);")}>Pikachu VMAX</div><div className="cg-num" style={s("font-size:12px; color:var(--muted-2); font-weight:600;")}>$88</div></div>
              <div onClick={p.goDetail} style={s("background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:10px; cursor:pointer;")}><div style={s("height:118px; border-radius:10px; background:var(--thumb); margin-bottom:9px; position:relative;")}><span style={s("position:absolute; top:7px; left:7px; background:var(--ink); color:var(--bg); font-family:'DM Mono',monospace; font-size:9px; padding:2px 6px; border-radius:6px;")}>PSA 10</span></div><div style={s("font-weight:700; font-size:13px; color:var(--ink);")}>C. McDavid</div><div className="cg-num" style={s("font-size:12px; color:var(--pos); font-weight:600;")}>$540</div></div>
            </div>
          </div>
          <div style={s("flex:none; height:86px; background:var(--footer); border-top:1px solid var(--line); display:flex; align-items:flex-start; padding:12px 24px 0;")}>
            <div onClick={p.goHome} style={s("flex:1; display:flex; flex-direction:column; align-items:center; gap:4px; cursor:pointer;")}><svg width="22" height="22" viewBox="0 0 22 22" style={s("fill:none; stroke:#9aa6a0; stroke-width:1.8")} strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l8-6 8 6v9a1 1 0 0 1-1 1h-4v-6H8v6H4a1 1 0 0 1-1-1Z"/></svg><span style={s("font-size:10px; color:#9aa6a0;")}>Home</span></div>
            <div onClick={p.goCollection} style={s("flex:1; display:flex; flex-direction:column; align-items:center; gap:4px; cursor:pointer;")}><svg width="22" height="22" viewBox="0 0 22 22" style={s("fill:none; stroke:var(--accent); stroke-width:1.8")} strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="16" height="12" rx="2"/><path d="M7 5V3h8v2"/></svg><span style={s("font-size:10px; color:var(--accent-deep); font-weight:600;")}>Collection</span></div>
            <div style={s("flex:1; display:flex; justify-content:center;")}><div onClick={p.goScan} style={s("width:58px; height:58px; border-radius:20px; background:#00c2a8; margin-top:-22px; display:flex; align-items:center; justify-content:center; box-shadow:0 8px 20px rgba(0,194,168,.4); cursor:pointer;")}><svg width="26" height="26" viewBox="0 0 26 26" style={s("fill:none; stroke:#04332c; stroke-width:2.2")} strokeLinecap="round" strokeLinejoin="round"><path d="M4 8.5A2.5 2.5 0 0 1 6.5 6h1.2L9.5 3.5h7L18.3 6h1.2A2.5 2.5 0 0 1 22 8.5V18a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2Z"/><circle cx="13" cy="13" r="4"/></svg></div></div>
            <div onClick={p.goInsights} style={s("flex:1; display:flex; flex-direction:column; align-items:center; gap:4px; cursor:pointer;")}><svg width="22" height="22" viewBox="0 0 22 22" style={s("fill:none; stroke:#9aa6a0; stroke-width:1.8")} strokeLinecap="round" strokeLinejoin="round"><path d="M3 18V9M9 18V4M15 18v-7"/></svg><span style={s("font-size:10px; color:#9aa6a0;")}>Insights</span></div>
            <div onClick={p.goProfile} style={s("flex:1; display:flex; flex-direction:column; align-items:center; gap:4px; cursor:pointer;")}><svg width="22" height="22" viewBox="0 0 22 22" style={s("fill:none; stroke:#9aa6a0; stroke-width:1.8")} strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="7" r="4"/><path d="M3 19a8 8 0 0 1 16 0"/></svg><span style={s("font-size:10px; color:#9aa6a0;")}>Profile</span></div>
          </div>
        </div>
  );
}
