import React from 'react';
import { s } from '../style.js';

export default function Grade(p) {
  return (
<div style={s("height:100%; display:flex; flex-direction:column; animation:cg-fade .3s ease;")}>
          <div style={s("flex:none; display:flex; align-items:center; justify-content:space-between; padding:4px 20px 12px;")}>
            <div onClick={p.goHome} style={s("width:38px; height:38px; border-radius:50%; background:var(--surface); border:1px solid var(--line-2); display:flex; align-items:center; justify-content:center; cursor:pointer;")}><svg width="9" height="16" viewBox="0 0 9 16" style={s("fill:none; stroke:var(--ink); stroke-width:2")} strokeLinecap="round" strokeLinejoin="round"><path d="M8 1 1 8l7 7"/></svg></div>
            <div style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:17px; color:var(--ink);")}>Grade Result</div>
            <div onClick={p.toggleTheme} style={s("display:flex; align-items:center; background:var(--surface); border:1px solid var(--line-2); border-radius:100px; padding:3px; cursor:pointer;")}><span style={s("width:26px; height:26px; border-radius:50%; background:var(--theme-sun-bg,transparent); display:flex; align-items:center; justify-content:center;")}><svg width="13" height="13" viewBox="0 0 14 14" style={s("fill:none; stroke:var(--muted); stroke-width:1.5")} strokeLinecap="round"><circle cx="7" cy="7" r="3"/><path d="M7 1v1.5M7 11.5V13M1 7h1.5M11.5 7H13M2.8 2.8l1 1M10.2 10.2l1 1M11.2 2.8l-1 1M3.8 10.2l-1 1"/></svg></span><span style={s("width:26px; height:26px; display:flex; align-items:center; justify-content:center;")}><svg width="13" height="13" viewBox="0 0 14 14" style={s("fill:none; stroke:var(--muted); stroke-width:1.5")} strokeLinecap="round" strokeLinejoin="round"><path d="M11.5 8.5A5 5 0 1 1 5.5 2.5a4 4 0 0 0 6 6Z"/></svg></span></div>
          </div>
          <div style={s("flex:1; overflow:hidden; padding:2px 20px 16px;")}>
            <div style={s("display:flex; gap:14px; align-items:stretch; margin-bottom:16px;")}>
              <div style={s("width:104px; flex:none; border-radius:16px; overflow:hidden; position:relative; background:var(--thumb); border:1px solid var(--line-2);")}><div style={s("position:absolute; top:8px; left:8px; background:var(--ink); color:var(--bg); font-family:'DM Mono',monospace; font-size:9px; padding:3px 6px; border-radius:6px;")}>FRONT</div></div>
              <div style={s("flex:1; background:var(--slab); border:1px solid var(--line-2); border-radius:20px; padding:16px 18px; color:#fff; position:relative; overflow:hidden; display:flex; flex-direction:column; justify-content:space-between;")}>
                <div style={s("position:absolute; right:-30px; top:-30px; width:120px; height:120px; border-radius:50%; background:radial-gradient(circle,#00c2a8 0%,rgba(0,194,168,0) 70%); opacity:.45;")}></div>
                <div style={s("font-family:'DM Mono',monospace; font-size:10px; letter-spacing:0.12em; color:#7fe9d8;")}>PREDICTED · PSA</div>
                <div style={s("display:flex; align-items:baseline; gap:8px;")}><span style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:800; font-size:58px; line-height:0.85; letter-spacing:-0.02em; color:var(--grade-num);")}>9</span><span style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:800; font-size:17px; color:#7fe9d8;")}>MINT</span></div>
                <div style={s("display:flex; align-items:center; gap:6px; font-size:12px; color:#9fb0aa;")}><span style={s("width:7px; height:7px; border-radius:50%; background:#00c2a8;")}></span><span className="cg-num">92% confidence</span></div>
              </div>
            </div>
            <div style={s("margin-bottom:14px;")}><div style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:19px; color:var(--ink);")}>Charizard ex</div><div style={s("font-family:'DM Mono',monospace; font-size:11px; color:var(--muted); margin-top:3px;")}>POKÉMON 151 · #199 · HOLO</div></div>
            <div style={s("display:grid; grid-template-columns:1fr 1fr; gap:10px; margin-bottom:14px;")}>
              <div style={s("background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:13px 14px;")}><div style={s("display:flex; justify-content:space-between; align-items:baseline;")}><span style={s("font-family:'DM Mono',monospace; font-size:10px; color:var(--muted); letter-spacing:0.06em;")}>CENTERING</span><span className="cg-num" style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:20px; color:var(--ink);")}>8.5</span></div><div style={s("height:4px; background:var(--track); border-radius:3px; margin-top:9px;")}><div style={s("width:85%; height:100%; background:#00c2a8; border-radius:3px;")}></div></div></div>
              <div style={s("background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:13px 14px;")}><div style={s("display:flex; justify-content:space-between; align-items:baseline;")}><span style={s("font-family:'DM Mono',monospace; font-size:10px; color:var(--muted); letter-spacing:0.06em;")}>CORNERS</span><span className="cg-num" style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:20px; color:var(--ink);")}>9.0</span></div><div style={s("height:4px; background:var(--track); border-radius:3px; margin-top:9px;")}><div style={s("width:90%; height:100%; background:#00c2a8; border-radius:3px;")}></div></div></div>
              <div style={s("background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:13px 14px;")}><div style={s("display:flex; justify-content:space-between; align-items:baseline;")}><span style={s("font-family:'DM Mono',monospace; font-size:10px; color:var(--muted); letter-spacing:0.06em;")}>EDGES</span><span className="cg-num" style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:20px; color:var(--ink);")}>9.5</span></div><div style={s("height:4px; background:var(--track); border-radius:3px; margin-top:9px;")}><div style={s("width:95%; height:100%; background:#00c2a8; border-radius:3px;")}></div></div></div>
              <div style={s("background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:13px 14px;")}><div style={s("display:flex; justify-content:space-between; align-items:baseline;")}><span style={s("font-family:'DM Mono',monospace; font-size:10px; color:var(--muted); letter-spacing:0.06em;")}>SURFACE</span><span className="cg-num" style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:20px; color:var(--ink);")}>9.0</span></div><div style={s("height:4px; background:var(--track); border-radius:3px; margin-top:9px;")}><div style={s("width:90%; height:100%; background:#00c2a8; border-radius:3px;")}></div></div></div>
            </div>
            <div style={s("background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:14px 16px; margin-bottom:12px;")}>
              <div style={s("display:flex; justify-content:space-between; font-family:'DM Mono',monospace; font-size:11px; color:var(--muted); margin-bottom:9px;")}><span>CENTERING L/R</span><span className="cg-num" style={s("color:var(--ink); font-weight:500;")}>55 / 45</span></div>
              <div style={s("height:8px; background:var(--track); border-radius:3px; position:relative; overflow:hidden;")}><div style={s("position:absolute; left:0; top:0; width:55%; height:100%; background:#00c2a8;")}></div><div style={s("position:absolute; left:50%; top:-3px; width:1px; height:14px; background:var(--ink);")}></div></div>
            </div>
            <div style={s("background:var(--warn-bg); border:1px solid var(--warn-line); border-radius:16px; padding:13px 16px; display:flex; gap:11px;")}><div style={s("width:24px; height:24px; flex:none; border-radius:50%; background:#f0a83a; display:flex; align-items:center; justify-content:center; color:var(--warn-dot-ink); font-weight:800; font-size:13px;")}>?</div><div><div style={s("font-weight:700; font-size:13px; color:var(--warn-ink);")}>Why not a 10?</div><div style={s("font-size:12px; line-height:1.45; color:var(--warn-sub);")}>Centering sits slightly left (55/45). Corners are sharp.</div></div></div>
          </div>
          <div style={s("flex:none; padding:12px 20px 14px; background:var(--footer); border-top:1px solid var(--line); display:flex; gap:10px;")}>
            <div onClick={p.goCollection} style={s("flex:none; width:50px; height:50px; border-radius:14px; background:var(--surface-2); display:flex; align-items:center; justify-content:center; cursor:pointer;")}><svg width="18" height="18" viewBox="0 0 18 18" style={s("fill:none; stroke:var(--ink); stroke-width:1.6")} strokeLinecap="round" strokeLinejoin="round"><path d="M14 16V8a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v8m6-9V3a1 1 0 0 1 1-1h0a1 1 0 0 1 1 1v4"/></svg></div>
            <div onClick={p.goRoi} style={s("flex:1; height:50px; border-radius:14px; background:#00c2a8; display:flex; align-items:center; justify-content:center; color:#04332c; font-weight:700; font-size:15px; cursor:pointer;")}>See ROI · $58 net</div>
          </div>
        </div>
  );
}
