import React from 'react';
import { s } from '../style.js';

export default function Home(p) {
  return (
<div style={s("height:100%; display:flex; flex-direction:column; animation:cg-fade .3s ease;")}>
          <div style={s("flex:none; display:flex; align-items:center; justify-content:space-between; padding:4px 20px 10px;")}>
            <div onClick={p.goProfile} style={s("display:flex; align-items:center; gap:11px; cursor:pointer;")}><div style={s("width:40px; height:40px; border-radius:50%; background:linear-gradient(135deg,#00c2a8,#5b6cff);")}></div><div><div style={s("font-size:12px; color:var(--muted);")}>Good evening</div><div style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:16px; color:var(--ink); line-height:1;")}>Alex</div></div></div>
            <div style={s("display:flex; gap:10px;")}>
              <div style={s("width:38px; height:38px; border-radius:50%; background:var(--surface); border:1px solid var(--line-2); display:flex; align-items:center; justify-content:center;")}><svg width="16" height="16" viewBox="0 0 16 16" style={s("fill:none; stroke:var(--ink); stroke-width:1.6")} strokeLinecap="round"><circle cx="7" cy="7" r="5"/><path d="m14 14-3.5-3.5"/></svg></div>
              <div style={s("width:38px; height:38px; border-radius:50%; background:var(--surface); border:1px solid var(--line-2); display:flex; align-items:center; justify-content:center; position:relative;")}><svg width="16" height="16" viewBox="0 0 16 16" style={s("fill:none; stroke:var(--ink); stroke-width:1.6")} strokeLinecap="round" strokeLinejoin="round"><path d="M8 2a4 4 0 0 0-4 4c0 4-2 5-2 5h12s-2-1-2-5a4 4 0 0 0-4-4ZM6.5 13.5a1.5 1.5 0 0 0 3 0"/></svg><span style={s("position:absolute; top:7px; right:8px; width:8px; height:8px; border-radius:50%; background:#f0533f; border:2px solid var(--surface);")}></span></div>
            </div>
          </div>
          <div style={s("flex:1; overflow:hidden; padding:4px 20px 0;")}>
            <div style={s("background:var(--slab); border-radius:24px; padding:20px; color:#fff; margin-bottom:16px; position:relative; overflow:hidden; border:1px solid var(--line-2);")}>
              <div style={s("position:absolute; right:-30px; top:-30px; width:140px; height:140px; border-radius:50%; background:radial-gradient(circle,#00c2a8 0%,rgba(0,194,168,0) 70%); opacity:.45;")}></div>
              <div style={s("font-family:'DM Mono',monospace; font-size:11px; letter-spacing:0.1em; color:#9fb0aa;")}>PORTFOLIO VALUE</div>
              <div className="cg-num" style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:800; font-size:40px; letter-spacing:-0.02em; margin:6px 0 4px;")}>$12,480</div>
              <div style={s("display:flex; align-items:center; gap:8px; margin-bottom:16px;")}><span style={s("display:flex; align-items:center; gap:4px; background:rgba(24,179,104,.18); color:#5ee49f; font-weight:700; font-size:12px; padding:3px 9px; border-radius:8px;")}><svg width="10" height="10" viewBox="0 0 10 10" style={s("fill:none; stroke:#5ee49f; stroke-width:2")} strokeLinecap="round" strokeLinejoin="round"><path d="M2 7 7 2M4 2h3v3"/></svg><span className="cg-num">+8.4%</span></span><span className="cg-num" style={s("font-size:12px; color:#9fb0aa;")}>+$968 this month</span></div>
              <svg width="100%" height="52" viewBox="0 0 320 52" preserveAspectRatio="none"><polyline points="0,40 40,38 80,42 120,30 160,33 200,22 240,26 280,12 320,8" style={s("fill:none; stroke:#00c2a8; stroke-width:2.5")} strokeLinecap="round" strokeLinejoin="round"/><polyline points="0,40 40,38 80,42 120,30 160,33 200,22 240,26 280,12 320,8 320,52 0,52" style={s("fill:rgba(0,194,168,.12); stroke:none")}/></svg>
            </div>
            <div style={s("display:flex; gap:10px; margin-bottom:16px;")}>
              <div style={s("flex:1; background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:13px;")}><div className="cg-num" style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:20px; color:var(--ink);")}>342</div><div style={s("font-size:11px; color:var(--muted-2);")}>Cards</div></div>
              <div style={s("flex:1; background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:13px;")}><div className="cg-num" style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:20px; color:var(--ink);")}>61</div><div style={s("font-size:11px; color:var(--muted-2);")}>Graded</div></div>
              <div style={s("flex:1; background:var(--surface); border:1px solid var(--line); border-radius:16px; padding:13px;")}><div className="cg-num" style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:20px; color:var(--accent-deep);")}>47%</div><div style={s("font-size:11px; color:var(--muted-2);")}>Gem rate</div></div>
            </div>
            <div style={s("display:flex; justify-content:space-between; align-items:center; margin-bottom:10px;")}><span style={s("font-weight:700; font-size:15px; color:var(--ink);")}>Recent grades</span><span onClick={p.goCollection} style={s("font-size:13px; color:var(--accent-deep); font-weight:600; cursor:pointer;")}>See all</span></div>
            <div style={s("display:flex; flex-direction:column; gap:8px;")}>
              <div onClick={p.goDetail} style={s("display:flex; align-items:center; gap:12px; background:var(--surface); border:1px solid var(--line); border-radius:14px; padding:10px; cursor:pointer;")}><div style={s("width:38px; height:52px; flex:none; border-radius:7px; background:var(--thumb);")}></div><div style={s("flex:1;")}><div style={s("font-weight:700; font-size:14px; color:var(--ink);")}>Charizard ex</div><div style={s("font-size:12px; color:var(--muted-2);")}>Pokémon 151 · #199</div></div><div style={s("text-align:right;")}><div style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:16px; color:var(--ink);")}>PSA 9</div><div className="cg-num" style={s("font-size:12px; color:var(--pos);")}>$430</div></div></div>
              <div onClick={p.goDetail} style={s("display:flex; align-items:center; gap:12px; background:var(--surface); border:1px solid var(--line); border-radius:14px; padding:10px; cursor:pointer;")}><div style={s("width:38px; height:52px; flex:none; border-radius:7px; background:var(--thumb);")}></div><div style={s("flex:1;")}><div style={s("font-weight:700; font-size:14px; color:var(--ink);")}>Connor Bedard RC</div><div style={s("font-size:12px; color:var(--muted-2);")}>23-24 UD Young Guns</div></div><div style={s("text-align:right;")}><div style={s("font-family:'Bricolage Grotesque',sans-serif; font-weight:700; font-size:16px; color:var(--ink);")}>PSA 9.5</div><div className="cg-num" style={s("font-size:12px; color:var(--pos);")}>$310</div></div></div>
            </div>
          </div>
          
          <div style={s("flex:none; height:86px; background:var(--footer); border-top:1px solid var(--line); display:flex; align-items:flex-start; padding:12px 24px 0;")}>
            <div onClick={p.goHome} style={s("flex:1; display:flex; flex-direction:column; align-items:center; gap:4px; cursor:pointer;")}><svg width="22" height="22" viewBox="0 0 22 22" style={s("fill:none; stroke:var(--accent); stroke-width:1.8")} strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l8-6 8 6v9a1 1 0 0 1-1 1h-4v-6H8v6H4a1 1 0 0 1-1-1Z"/></svg><span style={s("font-size:10px; color:var(--accent-deep); font-weight:600;")}>Home</span></div>
            <div onClick={p.goCollection} style={s("flex:1; display:flex; flex-direction:column; align-items:center; gap:4px; cursor:pointer;")}><svg width="22" height="22" viewBox="0 0 22 22" style={s("fill:none; stroke:#9aa6a0; stroke-width:1.8")} strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="5" width="16" height="12" rx="2"/><path d="M7 5V3h8v2"/></svg><span style={s("font-size:10px; color:#9aa6a0;")}>Collection</span></div>
            <div style={s("flex:1; display:flex; justify-content:center;")}><div onClick={p.goScan} style={s("width:58px; height:58px; border-radius:20px; background:#00c2a8; margin-top:-22px; display:flex; align-items:center; justify-content:center; box-shadow:0 8px 20px rgba(0,194,168,.4); cursor:pointer;")}><svg width="26" height="26" viewBox="0 0 26 26" style={s("fill:none; stroke:#04332c; stroke-width:2.2")} strokeLinecap="round" strokeLinejoin="round"><path d="M4 8.5A2.5 2.5 0 0 1 6.5 6h1.2L9.5 3.5h7L18.3 6h1.2A2.5 2.5 0 0 1 22 8.5V18a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2Z"/><circle cx="13" cy="13" r="4"/></svg></div></div>
            <div onClick={p.goInsights} style={s("flex:1; display:flex; flex-direction:column; align-items:center; gap:4px; cursor:pointer;")}><svg width="22" height="22" viewBox="0 0 22 22" style={s("fill:none; stroke:#9aa6a0; stroke-width:1.8")} strokeLinecap="round" strokeLinejoin="round"><path d="M3 18V9M9 18V4M15 18v-7"/></svg><span style={s("font-size:10px; color:#9aa6a0;")}>Insights</span></div>
            <div onClick={p.goProfile} style={s("flex:1; display:flex; flex-direction:column; align-items:center; gap:4px; cursor:pointer;")}><svg width="22" height="22" viewBox="0 0 22 22" style={s("fill:none; stroke:#9aa6a0; stroke-width:1.8")} strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="7" r="4"/><path d="M3 19a8 8 0 0 1 16 0"/></svg><span style={s("font-size:10px; color:#9aa6a0;")}>Profile</span></div>
          </div>
        </div>
  );
}
